spring:
  application:
    name: social-graph-microservice

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: social-graph-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
            json:
                trusted:
                    packages: "com.bestpick.kafka.events"

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: ${LOCAL_NEO4J_SOCIALGRAPHDB_PASSWORD}

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

