spring:
  neo4j:
    uri: bolt://neo4j-social-graph:7687
    authentication:
      username: neo4j
      password: ${NEO4J_SOCIALGRAPHDB_PASSWORD}
      
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka