spring:
    application:
        name: text-posts-microservice
    data:
        mongodb:
            uri: mongodb://localhost:27017/text-posts-microservice
server:
    port: 0
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka