spring:
  datasource:
    url: jdbc:postgresql://postgres-users:5433/bestpick-users-db
    username: ${POSTGRES_USERSDB_USER}
    password: ${POSTGRES_USERSDB_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

profileImageUploadPath: ${PROFILE_IMAGES_UPLOAD_PATH}